# Common configuration for Breadcrumb guidance system


# System Settings
system:
  #How fast for the control loop to operate at
  nav_rate: 25.0
  #Timeout for the contact with the mav in seconds
  state_timeout: 5.0
  pos_timeout: 0.2
  #Frame of reference to output velocity goals
  vel_frame: "body"

# Flight Presets
guidance:
  #Home should be in the air, most likely above landing
  home_x: 0.0
  home_y: 0.0
  home_z: 1.0
  home_h: 0.0
  #Takeoff Height will be were the UAV rises to on takeoff
  takeoff_height: 1.0

# Horizontal Position Controller
pos_xy_pid:
  p: 0.4
  i: 0.0
  d: 0.01
  min: -1.0
  max: 1.0

# Vertical Position Controller
pos_z_pid:
  p: 1.0
  i: 0.0
  d: 0.0
  min: -0.5
  max: 1.0

# Heading Rate Controller
h_pid:
  p: 0.5
  i: 0.0
  d: 0.05
  min: -0.8 #radians per second
  max: 0.8  #radians per second


#	P		I		D		Max		Output
#	0.4		0.0		0.0		10.0	//XY Position
#	1.0		0.0		0.0		10.0	//Z Position

#	0.2		0.2		0.005	0.5		//XY Vel
#	0.4		0.0		2.0		1.0		//Z Vel

